# Generated by Django 5.1.2 on 2024-12-08 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='space_logos/')),
                ('header_title', models.CharField(max_length=255)),
                ('custom_message', models.TextField()),
                ('questions', models.TextField(help_text='Add up to 5 questions separated by new lines')),
                ('extra_information', models.JSONField(blank=True, default=dict)),
                ('collection_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('both', 'Text and Video')], default='text', max_length=10)),
                ('star_ratings_enabled', models.BooleanField(default=False)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('button_color', models.CharField(default='#000000', max_length=7)),
                ('language', models.CharField(default='English', max_length=50)),
                ('auto_translate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialEmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_template', models.CharField(default='Thank you for your testimonial, {name}!', max_length=255)),
                ('body_template', models.TextField(default='Hey {name},\n\nYou just made a testimonial to {brand_name} 🥳\n\n{testimonial_message}\nRetweet to spread the word 👇\n\nShare on {social_platform}\n\n— {sender_name} from {brand_name}\n\n💗 Love video testimonials? Sign up | Become an affiliate')),
                ('include_social_share_link', models.BooleanField(default=True)),
                ('social_share_link_template', models.URLField(blank=True, help_text='Template for social share link, e.g., https://twitter.com/intent/tweet?text={testimonial_message}', max_length=500, null=True)),
                ('sender_name', models.CharField(default='Deepak', max_length=255)),
                ('brand_name', models.CharField(default='Testimonial', max_length=255)),
                ('affiliate_signup_link', models.URLField(blank=True, help_text='Link for affiliate sign-up', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonialemailnotification', to='dashboard.space')),
            ],
        ),
        migrations.CreateModel(
            name='ThankYouPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thank_you_title', models.CharField(max_length=255)),
                ('thank_you_message', models.TextField(help_text='Markdown supported')),
                ('image', models.ImageField(blank=True, null=True, upload_to='thank_you_images/')),
                ('hide_image', models.BooleanField(default=False)),
                ('allow_social_sharing', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True, help_text='Redirect to your own page after submission', max_length=500, null=True)),
                ('reward_for_video', models.BooleanField(default=False, help_text='Automatically reward your customer for a video testimonial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thankyoupage', to='dashboard.space')),
            ],
        ),
    ]
