# Generated by Django 5.1.2 on 2024-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='logo',
            field=models.ImageField(blank=True, upload_to='space_logos/'),
        ),
    ]
